tested ExecSignUpController.js
karthik-NvY/T02-CS305 pull request #148
Opened 2024-04-16 12:38 UTC by saidatta993

2024-04-16 20:38 UTC, karthik-NvY requested changes

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +
Use beforeAll to include these two statements :
```
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)
```
See testing/sof-116 files for reference

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +        const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
delete 
```
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)

```

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +         const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
del 
```
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
         const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)

         // login with new user to get token.
         const newloginres = await request("http://localhost:8080").post('/user/login').send(newuserpacket)
```

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +        const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
del
```
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)
 const newloginres = await request("http://localhost:8080").post('/user/login').send(newuserpacket)
```

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +
use beforeAll to include:
```
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)
const newloginres = await request("http://localhost:8080").post('/user/login').send(newuserpacket)
```

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +          const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
remove 
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
 const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)
 const newloginres = await request("http://localhost:8080").post('/user/login').send(newuserpacket)

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +          const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
del 
const newuserpacket = {name:"name", password:"pass", email:"tmp@gmail.com"}
 const newres = await request("http://localhost:8080").post('/user/signup').send(newuserpacket)
 const newloginres = await request("http://localhost:8080").post('/user/login').send(newuserpacket)

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +        expect(res.status).toBe(201);
After creating fake user for testing you should delete the user.

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +
Make sure to also delete any test credentials created.

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +describe('deleteing Request', () => {
Same issues as above test cases.

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +    test('Return if user is successfully fetched ', async () => {
You are not fetching here . This is a deleting test case.😶

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +    });
There should be test case when multiple user requests are made in same ngo. i.e same user making duplicate request in the ngo. This should not be allowed.

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +        expect(res.status).toBe(404);
this is not an error. This simply means there are no users who requested for executive role.

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +    test('Return if no ngo_id is found in request list', async () => {
name of test case doesn't match the test

2024-04-16 20:38 UTC, karthik-NvY commented on server/__tests__/ExecSignup/ExecSignUp.test.js
> +        expect(res.body.message).toBe('No user found with that id');
in execcontroller, update role is changing the role of user to executive. It should change user in a particular NGO to executive. user_id + ngo_id

2024-04-16 20:38 UTC, karthik-NvY commented on server/controllers/ExecSignupController.js
>  			const updatedRole = await Roles.findOneAndUpdate(
update should happen user_id + ngo_id

2024-04-16 20:38 UTC, karthik-NvY commented on server/server.js
> +  app.use('/Request',ExecRoutes);
No need for a new base route. Add exec routes in /api

2024-04-22 19:54 UTC, PavithranGoud approved these changes

2024-04-22 19:55 UTC, karthik-NvY approved these changes

2024-04-22 19:55 UTC, merged