Login Signup page created
karthik-NvY/T02-CS305 pull request #42
Opened 2024-02-07 07:03 UTC by Doodhnath1

Login Signup created

2024-02-07 08:08 UTC, Div16s requested changes
Add proper comments in LoginSignup.jsx

2024-02-07 11:57 UTC, nk-gujjar approved these changes
centre the login page for different frame sizes.

2024-02-07 13:21 UTC, karthik-NvY commented
fixes #27 

Next time, create branch directly from the issue's page

2024-02-20 08:09 UTC, Div16s approved these changes

2024-02-20 08:09 UTC, closed without merging